name: Build and Push kubeai Docker image
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
    paths-ignore:
      - '**/README.md'
  pull_request:

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: kubeai-project/kubeai

jobs:
  build:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read # to fetch the repository content
      id-token: write # for signing attestation(s) with GitHub OIDC Token
    with:
      output: image
      push: true
      context: .
      file: Dockerfile
      target: runtime
      cache: true
      cache-scope: kubeai
      meta-images: ghcr.io/kubeai-project/kubeai
      meta-tags: |
        type=sha
      set-meta-labels: true
